DROP DATABASE IF EXIsts projetjava ;
create database projetjava;
use projetjava;

DROP TABLE IF EXISTS `article`;
CREATE TABLE IF NOT EXISTS `article` (
  `IDARTICLE` int(11) NOT NULL AUTO_INCREMENT,
  `DESIGNATION` char(30) DEFAULT NULL,
  `PRIX` float DEFAULT NULL,
  `CATEGORIE` char(30) DEFAULT NULL,
  PRIMARY KEY (`IDARTICLE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

INSERT INTO `article` (`IDARTICLE`, `DESIGNATION`, `PRIX`, `CATEGORIE`) VALUES
(1, 'Sandwich Poulet', 22, 'Sandwich'),
(2, 'Plat Spaghetti', 20, 'Plat');

DROP TABLE IF EXISTS `commande`;
CREATE TABLE IF NOT EXISTS `commande` (
  `IDCOMMANDE` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` varchar(50) DEFAULT NULL,
  `MONTANT` float DEFAULT '0',
  `PAYE` tinyint(1) DEFAULT '0',
  `numTable` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`IDCOMMANDE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

INSERT INTO `commande` (`IDCOMMANDE`, `DATE`, `MONTANT`, `PAYE`, `numTable`) VALUES
(5, '2019-01-06 05:02:04', 22, 0, 9),
(6, '2019-01-06 05:02:23', 22, 0, 13);

DROP TABLE IF EXISTS `detail_commande`;
CREATE TABLE IF NOT EXISTS `detail_commande` (
  `IDCOMMANDE` int(11) NOT NULL,
  `IDARTICLE` int(11) NOT NULL,
  `QUANTITE` int(11) DEFAULT NULL,
  `prixAchat` float NOT NULL,
  PRIMARY KEY (`IDCOMMANDE`,`IDARTICLE`),
  KEY `FK_DETAIL_COMMANDE` (`IDARTICLE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `detail_commande` (`IDCOMMANDE`, `IDARTICLE`, `QUANTITE`, `prixAchat`) VALUES
(5, 1, 1, 22),
(6, 1, 1, 22);

DROP TABLE IF EXISTS `employees`;
CREATE TABLE IF NOT EXISTS `employees` (
  `IDEMPLOYEE` int(11) NOT NULL AUTO_INCREMENT,
  `LOGIN` char(25) DEFAULT NULL,
  `MOTDEPASSE` char(25) DEFAULT NULL,
  `NOM` char(25) DEFAULT NULL,
  `PRENOM` char(25) DEFAULT NULL,
  PRIMARY KEY (`IDEMPLOYEE`),
  UNIQUE KEY `LOGIN` (`LOGIN`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

INSERT INTO `employees` (`IDEMPLOYEE`, `LOGIN`, `MOTDEPASSE`, `NOM`, `PRENOM`) VALUES
(1, 'admin', 'admin', 'Bourqadi', 'Amine');


ALTER TABLE `detail_commande`
  ADD CONSTRAINT `FK_DETAIL_COMMANDE` FOREIGN KEY (`IDARTICLE`) REFERENCES `article` (`IDARTICLE`),
  ADD CONSTRAINT `FK_DETAIL_COMMANDE2` FOREIGN KEY (`IDCOMMANDE`) REFERENCES `commande` (`IDCOMMANDE`) ON DELETE CASCADE;
COMMIT;


