/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kikisrestaurantmanager;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import MODEL.Commande;
import MODEL.TableModel;

/**
 *
 * @author Nada
 */
public class accesCommandeFrame extends javax.swing.JFrame implements ListSelectionListener {

    Commande C = new Commande();
    int idCommande;

    /**
     * Creates new form accesCommande
     */
    public accesCommandeFrame() {
        initComponents();
        C.CreerCommande();
    }
    MainMenu mainMenu;

    public accesCommandeFrame(MainMenu mn) {
        //     this.setUndecorated(true);
        mainMenu = mn;
        initComponents();
        C.CreerCommande();
        System.out.println("Commande créée");
        setLocationRelativeTo(mainMenu);

    }

    public accesCommandeFrame(MainMenu mn, int idTable) {
        //     this.setUndecorated(true);
        mainMenu = mn;
        initComponents();
        idCommande = C.CreerCommande();
        System.out.println("Commande créée");
        this.getContentPane().setBackground(Color.white);
        TxtCurrentTable.setText("Table " + idTable);
    }

    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
        mainMenu.setEnabled(true);
        mainMenu.setVisible(true);
    }

    public void RefreshCommande() {
        ResultSet details = C.AfficherDetail(idCommande);
        TableCommande.setModel(new TableModel(details));
    } // to refresh the order table 

    public void Refresh_Menu(String cat) {
        ResultSet articles = C.MenuCategorie(cat);
        Menu.setModel(new TableModel(articles));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableCommande = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Menu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        PanelSandwich = new javax.swing.JPanel();
        TxtSandwich = new javax.swing.JLabel();
        PanelBurger = new javax.swing.JPanel();
        TxtBurger = new javax.swing.JLabel();
        PanelPizza = new javax.swing.JPanel();
        TxtPizza = new javax.swing.JLabel();
        PanelShawarma = new javax.swing.JPanel();
        TxtShawarma = new javax.swing.JLabel();
        PanelPlat = new javax.swing.JPanel();
        TxtPlat = new javax.swing.JLabel();
        PanelDessert = new javax.swing.JPanel();
        TxtDessert = new javax.swing.JLabel();
        PanelBoisson = new javax.swing.JPanel();
        TxtBoisson = new javax.swing.JLabel();
        PanelPanini = new javax.swing.JPanel();
        TxtPanini = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        BtnAnnuler = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BtnConfirmer = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Compteur = new javax.swing.JSpinner();
        panelTotal = new javax.swing.JPanel();
        TxtCurrentTable = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtMontant = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LabelAdd = new javax.swing.JLabel();
        LabelDelete = new javax.swing.JLabel();
        btnTrash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));

        TableCommande.setBackground(new java.awt.Color(204, 204, 255));
        TableCommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableCommande);

        Menu.setBackground(new java.awt.Color(212, 208, 200));
        Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Menu);

        jPanel1.setBackground(new java.awt.Color(217, 195, 217));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PanelSandwich.setBackground(new java.awt.Color(217, 195, 217));
        PanelSandwich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelSandwichMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelSandwichMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSandwichMousePressed(evt);
            }
        });
        PanelSandwich.setLayout(new javax.swing.BoxLayout(PanelSandwich, javax.swing.BoxLayout.LINE_AXIS));

        TxtSandwich.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtSandwich.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtSandwich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bread_25px_1.png"))); // NOI18N
        TxtSandwich.setText("Sandwich");
        PanelSandwich.add(TxtSandwich);

        PanelBurger.setBackground(new java.awt.Color(217, 195, 217));
        PanelBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBurgerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBurgerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBurgerMousePressed(evt);
            }
        });
        PanelBurger.setLayout(new javax.swing.BoxLayout(PanelBurger, javax.swing.BoxLayout.LINE_AXIS));

        TxtBurger.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtBurger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Hamburger_25px_1.png"))); // NOI18N
        TxtBurger.setText("Burger");
        PanelBurger.add(TxtBurger);

        PanelPizza.setBackground(new java.awt.Color(217, 195, 217));
        PanelPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPizzaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPizzaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelPizzaMousePressed(evt);
            }
        });
        PanelPizza.setLayout(new javax.swing.BoxLayout(PanelPizza, javax.swing.BoxLayout.LINE_AXIS));

        TxtPizza.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Pizza_25px.png"))); // NOI18N
        TxtPizza.setText("Pizza");
        PanelPizza.add(TxtPizza);

        PanelShawarma.setBackground(new java.awt.Color(217, 195, 217));
        PanelShawarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelShawarmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelShawarmaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelShawarmaMousePressed(evt);
            }
        });
        PanelShawarma.setLayout(new javax.swing.BoxLayout(PanelShawarma, javax.swing.BoxLayout.LINE_AXIS));

        TxtShawarma.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtShawarma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtShawarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Wrap_25px.png"))); // NOI18N
        TxtShawarma.setText("Shawarma");
        PanelShawarma.add(TxtShawarma);

        PanelPlat.setBackground(new java.awt.Color(217, 195, 217));
        PanelPlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPlatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelPlatMousePressed(evt);
            }
        });
        PanelPlat.setLayout(new javax.swing.BoxLayout(PanelPlat, javax.swing.BoxLayout.LINE_AXIS));

        TxtPlat.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtPlat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtPlat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Meal_25px.png"))); // NOI18N
        TxtPlat.setText("Plat");
        PanelPlat.add(TxtPlat);

        PanelDessert.setBackground(new java.awt.Color(217, 195, 217));
        PanelDessert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDessertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDessertMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelDessertMousePressed(evt);
            }
        });
        PanelDessert.setLayout(new javax.swing.BoxLayout(PanelDessert, javax.swing.BoxLayout.LINE_AXIS));

        TxtDessert.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtDessert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDessert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Confectionery_25px_3.png"))); // NOI18N
        TxtDessert.setText("Dessert");
        PanelDessert.add(TxtDessert);

        PanelBoisson.setBackground(new java.awt.Color(217, 195, 217));
        PanelBoisson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBoissonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBoissonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBoissonMousePressed(evt);
            }
        });

        TxtBoisson.setFont(new java.awt.Font("SimHei", 0, 13)); // NOI18N
        TxtBoisson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cocktail_25px_1.png"))); // NOI18N
        TxtBoisson.setText("Boisson");

        javax.swing.GroupLayout PanelBoissonLayout = new javax.swing.GroupLayout(PanelBoisson);
        PanelBoisson.setLayout(PanelBoissonLayout);
        PanelBoissonLayout.setHorizontalGroup(
            PanelBoissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtBoisson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBoissonLayout.setVerticalGroup(
            PanelBoissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtBoisson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelPanini.setBackground(new java.awt.Color(217, 195, 217));
        PanelPanini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPaniniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPaniniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelPaniniMousePressed(evt);
            }
        });
        PanelPanini.setLayout(new javax.swing.BoxLayout(PanelPanini, javax.swing.BoxLayout.LINE_AXIS));

        TxtPanini.setFont(new java.awt.Font("SimHei", 0, 14)); // NOI18N
        TxtPanini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtPanini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Hot_Dog_25px.png"))); // NOI18N
        TxtPanini.setText("Panini");
        PanelPanini.add(TxtPanini);
        PanelPanini.add(filler1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelPanini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDessert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPlat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelShawarma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(PanelPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBurger, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSandwich, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBoisson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(PanelBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPanini, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelShawarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BtnAnnuler.setBackground(new java.awt.Color(204, 204, 204));
        BtnAnnuler.setText("Annuler");
        BtnAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAnnulerMouseClicked(evt);
            }
        });
        BtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnnulerActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Commande");

        BtnConfirmer.setBackground(new java.awt.Color(204, 204, 204));
        BtnConfirmer.setText("Confirmer");
        BtnConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmerActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Menu");

        Compteur.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Compteur.setValue(1);

        panelTotal.setBackground(new java.awt.Color(217, 195, 217));
        panelTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTotal.setLayout(new java.awt.BorderLayout());

        TxtCurrentTable.setBackground(new java.awt.Color(255, 255, 255));
        TxtCurrentTable.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        TxtCurrentTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtCurrentTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Service_Bell_32px.png"))); // NOI18N
        TxtCurrentTable.setText("Current Table");
        panelTotal.add(TxtCurrentTable, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Rod", 0, 13)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bill_25px.png"))); // NOI18N
        jLabel1.setText("TOTAL (MAD) :");

        TxtMontant.setFont(new java.awt.Font("Rod", 0, 13)); // NOI18N
        TxtMontant.setText("100 MAD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(TxtMontant)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(TxtMontant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel17.setText("Quantité");

        LabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_32px_2.png"))); // NOI18N
        LabelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelAddMousePressed(evt);
            }
        });

        LabelDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        LabelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelDeleteMousePressed(evt);
            }
        });

        btnTrash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_32px_1.png"))); // NOI18N
        btnTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrashMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(Compteur, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelAdd)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelDelete)
                                            .addGap(2, 2, 2)
                                            .addComponent(btnTrash))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Compteur, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnTrash))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfirmer)
                    .addComponent(BtnAnnuler))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAddMousePressed
        // Ajout de l'article dans detail_commande 
        int row = Menu.getSelectedRow();
        if (row != -1) {
            int id_article = Integer.parseInt(Menu.getValueAt(row, 0).toString());
            // found this (below) for spinners ( compteur dial quantité) 
            try {
                Compteur.commitEdit();
            } catch (java.text.ParseException e) {
                System.err.println("Prob de compteur " + e.getMessage());
            }
            int qu = (Integer) Compteur.getValue();
            if (C.CheckArticle(id_article, idCommande) == 1) {
                C.UpdateDetailCommande(id_article, idCommande, qu);
            } else {
                C.InsererDetailCommande(id_article, idCommande, qu);
            }
            // Affichage depuis la base de données dans la table TableCommande
            RefreshCommande();
        }
    }//GEN-LAST:event_LabelAddMousePressed


    private void LabelDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDeleteMousePressed
        int row = TableCommande.getSelectedRow();
        if (row != -1) {
            int qu = Integer.parseInt(TableCommande.getValueAt(row, 2).toString());
            int id_article = Integer.parseInt(TableCommande.getValueAt(row, 0).toString());
            if(qu==1){
                C.SupprimerArticleCommande(idCommande, id_article);
            }
            else
                C.UpdateDetailCommande(id_article, idCommande, -1);
            RefreshCommande();
            if(qu>1)
                TableCommande.setRowSelectionInterval(row, row);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelDeleteMousePressed

    private void PanelBoissonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBoissonMousePressed
        String cat = "Boisson";
        Refresh_Menu(cat);
    }//GEN-LAST:event_PanelBoissonMousePressed

    private void PanelPaniniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPaniniMousePressed
        String cat = "Panini";
        Refresh_Menu(cat);
// TODO add your handling code here:
    }//GEN-LAST:event_PanelPaniniMousePressed

    private void PanelDessertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDessertMousePressed
        String cat = "Dessert";
        Refresh_Menu(cat);
    }//GEN-LAST:event_PanelDessertMousePressed

    private void PanelPlatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPlatMousePressed
        String cat = "Plat";
        Refresh_Menu(cat);
    }//GEN-LAST:event_PanelPlatMousePressed

    private void PanelShawarmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelShawarmaMousePressed
        String cat = "Shawarma";
        Refresh_Menu(cat);

    }//GEN-LAST:event_PanelShawarmaMousePressed

    private void PanelPizzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPizzaMousePressed
        String cat = "Pizza";
        Refresh_Menu(cat);
    }//GEN-LAST:event_PanelPizzaMousePressed

    private void PanelBurgerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBurgerMousePressed
        String cat = "Burger";
        Refresh_Menu(cat);
    }//GEN-LAST:event_PanelBurgerMousePressed

    private void PanelSandwichMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSandwichMousePressed
        String cat = "Sandwich";
        Refresh_Menu(cat);
        PanelSandwich.setBackground(new java.awt.Color(193, 153, 255));
    }//GEN-LAST:event_PanelSandwichMousePressed

    private void PanelBoissonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBoissonMouseEntered
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));

        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBoissonMouseEntered

    private void PanelBoissonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBoissonMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBoissonMouseExited

    private void PanelPaniniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPaniniMouseEntered

        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));// TODO add your handling code here:
    }//GEN-LAST:event_PanelPaniniMouseEntered

    private void PanelSandwichMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSandwichMouseEntered

        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));// TODO add your handling code here:
    }//GEN-LAST:event_PanelSandwichMouseEntered

    private void PanelBurgerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBurgerMouseEntered
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBurgerMouseEntered

    private void PanelPizzaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPizzaMouseEntered
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));        // TODO add your handling code here:
    }//GEN-LAST:event_PanelPizzaMouseEntered

    private void PanelShawarmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelShawarmaMouseEntered
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));       // TODO add your handling code here:
    }//GEN-LAST:event_PanelShawarmaMouseEntered

    private void PanelPlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPlatMouseEntered
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204));        // TODO add your handling code here:
    }//GEN-LAST:event_PanelPlatMouseEntered

    private void PanelDessertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDessertMouseEntered
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(193, 153, 204)); // TODO add your handling code here:
    }//GEN-LAST:event_PanelDessertMouseEntered

    private void PanelPaniniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPaniniMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));// TODO add your handling code here:
    }//GEN-LAST:event_PanelPaniniMouseExited

    private void PanelSandwichMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSandwichMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));
// TODO add your handling code here:
    }//GEN-LAST:event_PanelSandwichMouseExited

    private void PanelBurgerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBurgerMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBurgerMouseExited

    private void PanelPizzaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPizzaMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));// TODO add your handling code here:
    }//GEN-LAST:event_PanelPizzaMouseExited

    private void PanelShawarmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelShawarmaMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));        // TODO add your handling code here:
    }//GEN-LAST:event_PanelShawarmaMouseExited

    private void PanelPlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPlatMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));        // TODO add your handling code here:
    }//GEN-LAST:event_PanelPlatMouseExited

    private void PanelDessertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDessertMouseExited
        JPanel src = (JPanel) evt.getSource();
        src.setBackground(new java.awt.Color(217, 195, 217));// TODO add your handling code here:
    }//GEN-LAST:event_PanelDessertMouseExited

    private void BtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnnulerActionPerformed
        this.dispose();
        C.AnnulerCommande(idCommande);
    }//GEN-LAST:event_BtnAnnulerActionPerformed

    private void BtnAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAnnulerMouseClicked

    }//GEN-LAST:event_BtnAnnulerMouseClicked

    private void BtnConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmerActionPerformed
        this.dispose();
        if (C.CheckCreation(idCommande) == 0) 
        {
            C.AnnulerCommande(idCommande);
        }
        

    }//GEN-LAST:event_BtnConfirmerActionPerformed

    private void btnTrashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrashMousePressed
        int row = TableCommande.getSelectedRow();
        if (row != -1) 
        {
            int id_article = Integer.parseInt(TableCommande.getValueAt(row, 0).toString());
            C.SupprimerArticleCommande(idCommande, id_article);
            RefreshCommande();
        }
    }//GEN-LAST:event_btnTrashMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accesCommandeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accesCommandeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accesCommandeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accesCommandeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accesCommandeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnnuler;
    private javax.swing.JButton BtnConfirmer;
    private javax.swing.JSpinner Compteur;
    private javax.swing.JLabel LabelAdd;
    private javax.swing.JLabel LabelDelete;
    private javax.swing.JTable Menu;
    private javax.swing.JPanel PanelBoisson;
    private javax.swing.JPanel PanelBurger;
    private javax.swing.JPanel PanelDessert;
    private javax.swing.JPanel PanelPanini;
    private javax.swing.JPanel PanelPizza;
    private javax.swing.JPanel PanelPlat;
    private javax.swing.JPanel PanelSandwich;
    private javax.swing.JPanel PanelShawarma;
    private javax.swing.JTable TableCommande;
    private javax.swing.JLabel TxtBoisson;
    private javax.swing.JLabel TxtBurger;
    private javax.swing.JLabel TxtCurrentTable;
    private javax.swing.JLabel TxtDessert;
    private javax.swing.JLabel TxtMontant;
    private javax.swing.JLabel TxtPanini;
    private javax.swing.JLabel TxtPizza;
    private javax.swing.JLabel TxtPlat;
    private javax.swing.JLabel TxtSandwich;
    private javax.swing.JLabel TxtShawarma;
    private javax.swing.JLabel btnTrash;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
